Add User Experience (UX) Section
NLeSC/guide pull request #233
Opened 2020-11-18 15:03 UTC by ctwhome

- [ ] I followed the [CONTRIBUTING guidelines](../blob/master/CONTRIBUTING.md).

2020-11-26 17:43 UTC, c-martinez commented on best_practices/user_experience.md
> +At eScience Center, we follow the principles and indications taught by [interaction-design.org](https://www.interaction-design.org/literature) when going through the iteration process of creating res
Do we follow these principles and indications? I don't think we currently do (maybe we should). 

Suggested rewording:
"The principles and indications taught by [interaction-design.org](https://www.interaction-design.org/literature) can be useful in the process of creating research software."

2020-11-26 17:45 UTC, c-martinez commented on best_practices/user_experience.md
> +<img src="https://user-images.githubusercontent.com/4195550/99543543-92942800-29b3-11eb-8def-940592bb1977.png" width="700" />
Did you make the image? Nice! Maybe we should add a licence statement?

2020-11-26 17:46 UTC, c-martinez commented on best_practices/user_experience.md
> +<img src="https://user-images.githubusercontent.com/4195550/99543973-13532400-29b4-11eb-9179-f74db459dfbe.png" width="700" />
Hmmm... are we allowed to use their image?

2020-11-26 17:48 UTC, c-martinez commented on best_practices/user_experience.md
> +When delivering software iteratively, one of the common approaches to follow is to define a Minimum Value Product that contains the minimum requirements. Often is forgotten in this approach to delive
👍

2020-11-26 17:48 UTC, c-martinez commented on best_practices/user_experience.md
> +MLP approach **focuses on essential features** instead of the bare minimum expected from a class software. The outcomes mush contains all elements in the pyramid being functional, reliable, usable, a
MVP?

2020-11-26 17:49 UTC, c-martinez commented on best_practices/user_experience.md
> +MLP approach **focuses on essential features** instead of the bare minimum expected from a class software. The outcomes mush contains all elements in the pyramid being functional, reliable, usable, a
mush -> must ?

2020-11-26 17:50 UTC, c-martinez requested changes
Looking good! Left a few comments, on how to improve it.

2020-11-30 08:01 UTC, ctwhome commented on best_practices/user_experience.md
> +At eScience Center, we follow the principles and indications taught by [interaction-design.org](https://www.interaction-design.org/literature) when going through the iteration process of creating res
That is indeed a much better approach. I was a bit bold there, kind of setting up a way, but I realize that is much better rephrasing it as you do. thanks

2020-11-30 08:12 UTC, ctwhome commented on best_practices/user_experience.md
> +<img src="https://user-images.githubusercontent.com/4195550/99543973-13532400-29b4-11eb-9179-f74db459dfbe.png" width="700" />
Yes, we can, but it needs to be appropriately credited. Here is their IP https://www.interaction-design.org/about/terms-of-use for this specific image.

2020-11-30 08:14 UTC, ctwhome commented on best_practices/user_experience.md
> +<img src="https://user-images.githubusercontent.com/4195550/99543973-13532400-29b4-11eb-9179-f74db459dfbe.png" width="700" />
here we go: Author/Copyright holder: Teo Yu Siang and Interaction Design Foundation. Copyright licence: CC BY-NC-SA 3.0

2020-11-30 08:55 UTC, ctwhome commented
I have implemented the comments and changes @c-martinez proposed.

2020-11-30 15:35 UTC, c-martinez approved these changes

2020-12-02 09:19 UTC, merged