Move link-checker to github actions
NLeSC/guide pull request #239
Opened 2020-12-15 12:45 UTC by c-martinez

- [X] I followed the [CONTRIBUTING guidelines](../blob/master/CONTRIBUTING.md).

Below, describe what this Pull Request adds:
This PR adds a github action for checking broken links, removing the need to do this on Travis.

2020-12-22 12:05 UTC, bouweandela requested changes
To *move* the link checker to GitHub actions, I would expect the travis tests would need to be removed as well? I see the action is not running yet, but I guess that is because it is not in `master` yet?

2021-01-04 08:55 UTC, c-martinez commented
Good point. I've removed the the travis files. Indeed action is not yet running because this is not yet merged, but you can see the action running on [my fork](https://github.com/c-martinez/guide/actions?query=workflow%3A%22Link+Checker%22)

2021-01-04 10:11 UTC, bouweandela commented
Great! Would it be possible to display only broken links? At the moment a lot of scrolling through the output is needed to find which links are broken.

2021-01-04 10:12 UTC, bouweandela commented on .github/workflows/link-checker.yml
> +            fi
Maybe you could also display the broken links here?

2021-01-04 10:15 UTC, bouweandela commented
There was also a check on broken links in changed files only, specifically for pull requests. Would it be possible to add that to GitHub actions too?

2021-01-04 16:55 UTC, c-martinez commented
Good point -- I've added an additional action for checking on pull requests.

I also noticed that link-checker action is deprecated in favour of (lychee-action)[https://github.com/lycheeverse/lychee-action], so this will work for the moment, but we should consider upgrading in the future.

2021-01-04 19:56 UTC, bouweandela approved these changes

2021-01-04 19:56 UTC, merged