update on publishing through pypi
NLeSC/guide pull request #323
Opened 2023-12-06 08:26 UTC by f-hafner

- [x] I followed the [CONTRIBUTING guidelines](../blob/main/CONTRIBUTING.md).

I propose a fix to #290:
- recommend Github actions as default for distributing packages through pypi; update links to documentation
- suggest workflow with testpypi and manual uploads with 2FA for debugging, based on the discussion in said issue

Notes
- I have not tried out the "new" manual way with 2FA
- I removed the link to the twine tutorial as it's outdated

Questions
- signing distribution packages is not described, but it's [here]( https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/ ) -- should I add something about it? 
- should the release workflow in the python template (the generated [README.dev.md](https://github.com/NLeSC/python-template/blob/main/%7B%7Bcookiecutter.directory_name%7D%7D/README.dev.md)) be synced with the changes made here?

2024-01-17 08:25 UTC, bouweandela requested changes
Thanks for the update! :sparkles: I would suggest reducing the amount of text a bit because that will make it easier to maintain: maybe remove the links to examples and the extensive explanation of how to use test pypi (link to an external resource describing this workflow instead)?

Updating the python-template so it follows what is described in the guide would be nice.

2024-01-17 08:25 UTC, bouweandela commented on best_practices/language_guides/python.md
> +#### [Build using conda](https://docs.conda.io/projects/conda-build/en/latest/user-guide/tutorials/index.html)
```suggestion
#### [Build using conda](https://conda-forge.org/docs/maintainer/adding_pkgs.html)
```
Shall we replace the link to directly point people to the right direction?

2024-01-18 13:36 UTC, f-hafner commented
I shortened as suggested. I will make an issue in the template.

2024-01-22 11:06 UTC, bouweandela approved these changes
Thanks!

2024-01-22 11:06 UTC, merged