add Python type hints
NLeSC/guide pull request #359
Opened 2024-10-21 20:30 UTC by egpbos

Added a subsection on type hints, following the discussion in #310. Also added a few cool libraries, e.g. FastAPI that was mentioned by Bouwe in #54 and Typer from the same author.

Fixes #310.

# Checklist

## SIGNIFICANT changes / additions, e.g. new chapters
- [x] I checked whether the contribution fits in [The Turing Way](https://github.com/the-turing-way/the-turing-way) before considering contributing to this Guide.
- [x] I discussed my contribution in an issue and took into account feedback.

## ALL contributions
- [ ] I previewed my changes locally using e.g. `python3 -m http.server 4000` and confirmed they work correctly.
- [x] I checked for broken links, e.g. using the link checker GitHub Action workflow, or locally by using ``docker run --init -it -v `pwd`:/docs lycheeverse/lychee /docs --config=docs/lychee.toml``, at least for the files I changed.
- [x] My name was added to the `CITATION.cff` file.

2024-10-22 07:08 UTC, bouweandela requested changes
Thanks @egpbos, very nice addition!

2024-10-22 07:08 UTC, bouweandela commented on language_guides/python.md
> +Such huge types clutter your code tremendously, so they are not typically encouraged.
```suggestion
```
I would leave this out. There is some discussion possible about the design choices of matplotlib and that is not the aim of our guide. How about saying that type hints are not practical if e.g. the researchers you are developing the code with are not comfortable with using them because they are too technical?

2024-10-22 07:08 UTC, bouweandela commented on language_guides/python.md
> +* [Typer](https://typer.tiangolo.com): make a CLI app by using type hints with runtime effects. Very low on boilerplate for simple cases, but also allows for more complex cases. Uses `click` internal
```suggestion
* [Typer](https://typer.tiangolo.com): make a command-line application by using type hints with runtime effects. Very low on boilerplate for simple cases, but also allows for more complex cases. Uses `click` internally.
```
To keep the text easy to understand for less technical people

2024-10-22 07:08 UTC, bouweandela commented on language_guides/python.md
> +This is why, for instance, NumPy arrays and ML library "tensor" types still (in 2024) have awkward type hinting.
Could you be more specific about what "ML library" you mean? And also write out the abbreviation, please

2024-10-22 07:08 UTC, bouweandela commented on language_guides/python.md
> +- [Mypy](https://mypy.readthedocs.io/en/stable/index.html): tool that checks whether your code uses types correctly.
Make this a bit broader by mentioning (or linking to a page with) alternatives? e.g. https://www.infoworld.com/article/2260170/4-python-type-checkers-to-keep-your-code-clean.html

2024-11-19 14:18 UTC, egpbos commented
@stefsmeets We talked today about [`attrs`](https://www.attrs.org/en/stable/) and how you used it for nested-yaml / dataclass validation and preferred it over Pydantic. In this PR, I happened to add a bit of text on Pydantic. I haven't looked at attrs yet, but do you think it makes sense to mention it in here as well? Or does it deserve a topic of its own? Is schema / data validation perhaps a useful topic for a section of the [data chapter](https://guide.esciencecenter.nl/#/technology/datasets)?

2024-11-19 15:29 UTC, stefsmeets commented
I think it makes sense, I find attrs to be much more approachable than pydantic. The attrs docs have a really nice section on comparing the different tools: https://www.attrs.org/en/stable/why.html

2024-11-20 07:56 UTC, egpbos commented
Briefly [browsing PROTEUS' use of attrs](https://github.com/search?q=repo%3AFormingWorlds%2FPROTEUS%20attrs&type=code), it seems like a nice lightweight tool for value validation. I'm not sure how (or even if) Pydantic handles this, but certainly seems useful. I don't think it should go under this PR, though, it's a topic independent of type hints.

2024-12-04 13:22 UTC, egpbos commented on language_guides/python.md
> +This is why, for instance, NumPy arrays and ML library "tensor" types still (in 2024) have awkward type hinting.
E.g. PyTorch, Tensorflow.

2024-12-04 13:23 UTC, egpbos commented on language_guides/python.md
> +- [Mypy](https://mypy.readthedocs.io/en/stable/index.html): tool that checks whether your code uses types correctly.
Sounds good! I just added the link above from a suggestion made in the issue, I think, but if you think yours is better I'm also fine with just replacing.

2024-12-04 13:24 UTC, egpbos commented on language_guides/python.md
> +Such huge types clutter your code tremendously, so they are not typically encouraged.
This was a very practical concrete example that I have run into in a recent project where typing becomes more a hassle than a benefit, that's why I mention it. Also, I think it's such a common package for research that it is not a bad example to give in any case.

2024-12-04 14:25 UTC, merged