Add shortcut on paragraph about assignment operator
NLeSC/guide pull request #367
Opened 2024-12-03 10:41 UTC by PabRod

# Changes in this PR
The `R` language kept evolving since we wrote this. It needs some updates

# Checklist

## SIGNIFICANT changes / additions, e.g. new chapters
- [ ] I checked whether the contribution fits in [The Turing Way](https://github.com/the-turing-way/the-turing-way) before considering contributing to this Guide.
- [ ] I discussed my contribution in an issue and took into account feedback.

## ALL contributions
- [ ] I previewed my changes locally using e.g. `python3 -m http.server 4000` and confirmed they work correctly.
- [ ] I checked for broken links, e.g. using the link checker GitHub Action workflow, or locally by using ``docker run --init -it -v `pwd`:/docs lycheeverse/lychee /docs --config=docs/lychee.toml``, at least for the files I changed.
- [ ] My name was added to the `CITATION.cff` file.

2024-12-03 12:39 UTC, PabRod commented on language_guides/r.md
>  One point in both style conventions that has resulted in some discussion is the '<-' syntax for variable assignment. In the majority of R tutorials and books you will see that authors use this syntax
This whole discussion about `<-` vs `=` seems a bit too long the scope fo this guide. Shall we consider reducing it to a link for those really interested? What do you think, @maltelueken?

2024-12-03 12:51 UTC, maltelueken commented on language_guides/r.md
> +## `%>%` and `|>`
Perhaps add here that `|>` requires R > 4.0.0 which makes code incompatible with some legacy code. Also, `%>%` is not a native R operator and requires the `magrittr` package as a dependency (which is loaded with almost all tidyverse packages). Lean packages might not want to rely on this dependency.

2024-12-03 12:52 UTC, maltelueken commented
Perhaps, we should also mention R Shiny?

2024-12-03 13:04 UTC, PabRod commented
The broken links check throws 14 errors, but none of them in the file I edited.

2024-12-03 13:05 UTC, PabRod commented
Ready to review and merge!

2024-12-03 13:08 UTC, PabRod commented on language_guides/r.md
> +## `%>%` and `|>`
Done!

2024-12-03 14:06 UTC, maltelueken approved these changes
I made a correction about the pipe operators (my bad, `|>` was introduced in R 4.1) and added a link to `Rcpp` for perfomant R code.

Otherwise, the PR looks really great. With the correction, it can be merged.

2024-12-03 14:06 UTC, maltelueken commented on language_guides/r.md
> +The first one is part of the `magrittr` package, and it gained so much popularity that it was added as part of native R since version 4.0.0. For the rest, they are entirely equivalent.
```suggestion
The first one is part of the `magrittr` package, and it gained so much popularity that a similar operator, `|>`, was added as part of native R since version 4.1.0. For details on the differences between the two, see this [blog post](https://www.tidyverse.org/blog/2023/04/base-vs-magrittr-pipe/).
```

2024-12-03 14:06 UTC, maltelueken commented on language_guides/r.md
> +* [`purrr`](https://purrr.tidyverse.org/) package. It contains many functional programming tools that can help you build optimized processes
```suggestion
* [`purrr`](https://purrr.tidyverse.org/) package. It contains many functional programming tools that can help you build optimized processes

If you need R code that is even more performant, consider implementing functions in C++ and calling them from R via the [`Rcpp`](https://www.rcpp.org/) package.
```

2024-12-03 14:18 UTC, c-martinez requested changes
I've suggested a couple of minor things to consider changing, but otherwise its looking great!

2024-12-03 14:18 UTC, c-martinez commented on language_guides/r.md
> +* When `x` is a list, `x[1]` is another list containing the first element, and `x[[1]]` is its **value**.
Is there a link to slicing in R?

2024-12-03 14:18 UTC, c-martinez commented on language_guides/r.md
> +* R does not need a notebook to program interactively. Instead we recommend to use [RStudio](https://posit.co/products/open-source/rstudio/), an IDE that is installed separately.
And maybe recommending R studio should be left for the IDE section

2024-12-03 14:18 UTC, c-martinez commented on language_guides/r.md
> +## The `<-` operator
For the scope of the guide, I thing we should just give a recommendation "we recommend using `->`" (or something like that ;-) ).

The discussion on why use different operators is interesting, but outside of the scope of the guide. Maybe we can provide a pointer to an existing discussion "For a heated debate on `=` vs `<-` read here...". If we can point to an existing one, great. Otherwise maybe we can write a blog post with such a debate and link to it from here :-)

2024-12-03 14:18 UTC, c-martinez commented on language_guides/r.md
> +Most of the templating is nativelly managed by the [`usethis`](https://usethis.r-lib.org/) package. Said this, these others can serve as inspiration:
```suggestion
Most of the templating is nativelly managed by the [`usethis`](https://usethis.r-lib.org/) package. Having said this, these others can serve as inspiration:
```

2024-12-03 14:18 UTC, c-martinez commented on language_guides/r.md
> +Most of the templating is nativelly managed by the [`usethis`](https://usethis.r-lib.org/) package. Said this, these others can serve as inspiration:
Also, maybe we should add (or point to) a snippet of code of how we recommend to use `usethis` as suggested in https://github.com/NLeSC/guide/issues/327

2024-12-03 21:01 UTC, bouweandela reviewed
The R chapter as it currently is contains a lot of what Wikipedia would call ["original research"](https://en.wikipedia.org/wiki/Wikipedia:No_original_research). It would be nice to replace this by a short introduction and references to established community standards.

2024-12-03 21:01 UTC, bouweandela commented on language_guides/r.md
>  # Coding style conventions
Instead of writing our own style guide, it would be better to link to existing resources. E.g. how about mentioning [styler](https://github.com/r-lib/styler) + [lintr](https://github.com/r-lib/lintr)? Or are there better alternatives?

2024-12-04 12:07 UTC, PabRod commented on language_guides/r.md
> +* When `x` is a list, `x[1]` is another list containing the first element, and `x[[1]]` is its **value**.
Slicing is the first of second episode of virtually any R tutorial out there. I prefer to stick to the main differences with Python.

2024-12-04 12:07 UTC, PabRod commented on language_guides/r.md
> +## The `<-` operator
A blog about this sounds like a great idea. What do you think, @maltelueken?

2024-12-04 12:11 UTC, PabRod commented on language_guides/r.md
> +Are you familiar with Python? Then you'll find these remarks useful:
@bouweandela I'd say **yes**, but this will imply a significant removal of @maltelueken's work. I'd like to know his opinion first.

2024-12-04 12:40 UTC, maltelueken commented on language_guides/r.md
> +Are you familiar with Python? Then you'll find these remarks useful:
I only took over the chapter last year, so the great majority of the chapter was written before that. For me, replacing sections with links to other resources is fine.

2024-12-04 12:43 UTC, maltelueken commented on language_guides/r.md
>  # Coding style conventions
I agree that we should mention those two packages. There is also `formatR`, but I am not sure how stable it is at the moment.

We could refer to the [tidyverse style guide](https://style.tidyverse.org/) as one option?

2024-12-05 10:39 UTC, PabRod commented on language_guides/r.md
> +Are you familiar with Python? Then you'll find these remarks useful:
```suggestion
Are you familiar with Python? Then kickstart your R journey by reading this [blog post](https://towardsdatascience.com/the-starter-guide-for-transitioning-your-python-projects-to-r-8de4122b04ad).
```

2024-12-05 10:44 UTC, PabRod commented on language_guides/r.md
>  # Coding style conventions
It would be good to clearly choose one. Do we have such a preference?

2024-12-05 10:51 UTC, PabRod commented on language_guides/r.md
> +* `read.table()` is sometimes faster than `read.csv()`
Fixed in https://github.com/NLeSC/guide/pull/367/commits/22fa014ef1a7d465f54874c827987ab0cf965a17.

2024-12-05 12:07 UTC, PabRod commented on language_guides/r.md
> +## The `<-` operator
There are already man blogs about this. @PabRod will take care of replacing the paragraph with a link to one of those.

2024-12-05 12:08 UTC, PabRod commented on language_guides/r.md
>  # Coding style conventions
We'll go for the tidyverse style. @PabRod will rewrite this section.

2024-12-05 13:11 UTC, c-martinez approved these changes

2024-12-05 14:23 UTC, merged

2024-12-05 14:24 UTC, egpbos commented
Awesome effort here, thanks all!